### ISSUE TITLE
Encoding of telnet not always be UTF-8.

### ISSUE THREAD

**Issue by sgqy** [niruix/sshwifty#4] opened 2019-09-14 00:39 UTC
Examples:
`ptt.cc` uses CP950.
`bbs.ustc.edu.cn` uses CP936.

**Comment by niruix** [comment] 2019-09-14 01:09
I'm still working on the Telnet part. For now, only simple Telnet server is supported. Sorry.

If you want to connect with `ppt.cc`, you can use their SSH host (login with user `bbsu`). `bbs.ustc.edu.cn` however, is currently unsupported :(

**Comment by niruix** [comment] 2019-09-14 15:47
Hello, @sgqy. 

Sorry to brother you, I just want to give you some heads up.

I've added a new feature that will allow user to setup the encoding for Telnet connection, which should fix the problem.

![Screenshot](https://user-images.githubusercontent.com/30656734/64910518-d2c1a000-d749-11e9-944e-2d992be3873e.png)

However, I don't have account any of the Telnet hosts that you mentioned above. Could you try out the new version to help confirm the problem is fixed?

I already updated the demo (https://sshwifty.herokuapp.com/#+Telnet:bbs.ustc.edu.cn%7Cgbk), please give it one a try.

I'll release a new version once the fix is confirmed. Thank you!

**Comment by niruix** [comment] 2019-09-17 02:52
Hello, a little bit more heads up:

I've tested the fix during these days, and committed few more changes to the software. It should know how to deal with the Telnet encoding issue now, once the correct encoding is selected, of course.

I'll close this issue as I believe the bug is fixed. If you feeling otherwise, please reopen it so I can investigate further more.

Thank you!

**Closed by niruix** 2019-09-17 02:52 UTC
Labels: awaiting feedback, bug
